In [149]:
from sklearn.datasets import load_iris
import pandas as pd
data_iris = load_iris()
iris_df= pd.DataFrame(data_iris.data, columns= data_iris.feature_names)
iris_df['encoded_target'] = data_iris.target
iris_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),encoded_target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [150]:
# Lidando com Dados Nulos e Corrompidos
iris_df.iloc[0, 0] = None 
iris_df.iloc[0, 1] = None
iris_df.iloc[0, 2] = None
iris_df.iloc[1, 0] = None
iris_df.iloc[4, 3] = None
iris_df.iloc[149, 2] = None
iris_df.iloc[3, 3] = -9999999999999999999999999999
#iris_df.iloc[149, 2] = "cwcwwc"
iris_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),encoded_target
0,NaN,NaN,NaN,2.000000e-01,0
1,NaN,3.0,1.4,2.000000e-01,0
2,4.7,3.2,1.3,2.000000e-01,0
3,4.6,3.1,1.5,-1.000000e+28,0
4,5.0,3.6,1.4,NaN,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.300000e+00,2
146,6.3,2.5,5.0,1.900000e+00,2
147,6.5,3.0,5.2,2.000000e+00,2
148,6.2,3.4,5.4,2.300000e+00,2
149,5.9,3.0,NaN,1.800000e+00,2

In [151]:
iris_df.isna()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),encoded_target
0,True,True,True,False,False
1,True,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,True,False
...,...,...,...,...,...
145,False,False,False,False,False
146,False,False,False,False,False
147,False,False,False,False,False
148,False,False,False,False,False
149,False,False,True,False,False

In [152]:
iris_df[iris_df.isna().any(axis=1)]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),encoded_target
0,NaN,NaN,NaN,0.2,0
1,NaN,3.0,1.4,0.2,0
4,5.0,3.6,1.4,NaN,0
149,5.9,3.0,NaN,1.8,2

In [153]:
iris_df_rem = iris_df.dropna()
iris_df_rem

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),encoded_target
2,4.7,3.2,1.3,2.000000e-01,0
3,4.6,3.1,1.5,-1.000000e+28,0
5,5.4,3.9,1.7,4.000000e-01,0
6,4.6,3.4,1.4,3.000000e-01,0
7,5.0,3.4,1.5,2.000000e-01,0
...,...,...,...,...,...
144,6.7,3.3,5.7,2.500000e+00,2
145,6.7,3.0,5.2,2.300000e+00,2
146,6.3,2.5,5.0,1.900000e+00,2
147,6.5,3.0,5.2,2.000000e+00,2
148,6.2,3.4,5.4,2.300000e+00,2

In [154]:
iris_df_mean = iris_df.fillna(iris_df.mean) ## subistituir pela média da coluna 
iris_df_zero = iris_df.fillna(0) # Subistituir por zero 
iris_df_valores_impossiveis = iris_df.fillna(-999) ## subistituir por valores impossiveis

In [155]:
iris_df_mean

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),encoded_target
0,<bound method DataFrame.mean of sepal len...,<bound method DataFrame.mean of sepal len...,<bound method DataFrame.mean of sepal len...,0.2,0
1,<bound method DataFrame.mean of sepal len...,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,-9999999999999999583119736832.0,0
4,5.0,3.6,1.4,<bound method DataFrame.mean of sepal len...,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,<bound method DataFrame.mean of sepal len...,1.8,2

In [156]:
iris_df_zero

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),encoded_target
0,0.0,0.0,0.0,2.000000e-01,0
1,0.0,3.0,1.4,2.000000e-01,0
2,4.7,3.2,1.3,2.000000e-01,0
3,4.6,3.1,1.5,-1.000000e+28,0
4,5.0,3.6,1.4,0.000000e+00,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.300000e+00,2
146,6.3,2.5,5.0,1.900000e+00,2
147,6.5,3.0,5.2,2.000000e+00,2
148,6.2,3.4,5.4,2.300000e+00,2
149,5.9,3.0,0.0,1.800000e+00,2

In [157]:
iris_df_valores_impossiveis

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),encoded_target
0,-999.0,-999.0,-999.0,2.000000e-01,0
1,-999.0,3.0,1.4,2.000000e-01,0
2,4.7,3.2,1.3,2.000000e-01,0
3,4.6,3.1,1.5,-1.000000e+28,0
4,5.0,3.6,1.4,-9.990000e+02,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.300000e+00,2
146,6.3,2.5,5.0,1.900000e+00,2
147,6.5,3.0,5.2,2.000000e+00,2
148,6.2,3.4,5.4,2.300000e+00,2
149,5.9,3.0,-999.0,1.800000e+00,2

In [ ]:
# Regularização de Dados OBS.: Dados incompativéis com apresentação da aula

from sklearn.preprocessing import MinMaxScaler
data_iris = load_iris()
iris_df= pd.DataFrame(data_iris.data, columns= data_iris.feature_names)
iris_df['encoded_target'] = data_iris.target
scaler = MinMaxScaler()
print(scaler.fit(iris_df))
novo_iris_df = scaler.transform(iris_df)
novo_iris_df = pd.DataFrame(
    novo_iris_df,
    columns=iris_df.columns
).round(2)
novo_iris_df

MinMaxScaler()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),encoded_target
0,0.22,0.62,0.07,0.04,0.0
1,0.17,0.42,0.07,0.04,0.0
2,0.11,0.50,0.05,0.04,0.0
3,0.08,0.46,0.08,0.04,0.0
4,0.19,0.67,0.07,0.04,0.0
...,...,...,...,...,...
145,0.67,0.42,0.71,0.92,1.0
146,0.56,0.21,0.68,0.75,1.0
147,0.61,0.42,0.71,0.79,1.0
148,0.53,0.58,0.75,0.92,1.0
149,0.44,0.42,0.69,0.71,1.0