In [73]:
from sklearn.datasets import load_iris
import pandas as pd
def iris_df():
    data_iris = load_iris()

    iris_df = pd.DataFrame(
        data_iris.data,
        columns=data_iris.feature_names
    )

    iris_df["encoded_target"] = data_iris.target

    return iris_df

In [74]:
df=iris_df()

In [75]:
def identificar_object(df):
    colunas_object = df.select_dtypes(include=['object']).columns.tolist()

    if colunas_object:
        print("Colunas do tipo 'object':")
        for coluna in colunas_object:
            print(f"- {coluna}")
    else:
        print("Não há colunas do tipo 'object'.")

# Exemplo de uso
identificar_object(df)

Não há colunas do tipo 'object'.

In [76]:
# lidando com dados nulos, substituição

df_mean = df.fillna(df.mean) ## subistituir pela média da coluna 
df_zero = df.fillna(0) # Subistituir por zero 
iris_df_valores_impossiveis = df.fillna(-999) ## subistituir por valores impossiveis

In [77]:
iris_df_mean

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),encoded_target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [78]:
iris_df_zero

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),encoded_target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [79]:
iris_df_valores_impossiveis

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),encoded_target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [80]:
df.loc[0, 'sepal_length'] = 'erro'
identificar_object(df)

Colunas do tipo 'object':
- sepal_length

/tmp/ipykernel_19530/266111243.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  colunas_object = df.select_dtypes(include=['object']).columns.tolist()

In [81]:
import random
df = iris_df()
linha = random.randint(0, len(df) - 1)
coluna = random.choice(df.select_dtypes(include="number").columns)

df[coluna] = df[coluna].astype(object)
df.loc[linha, coluna] = "erro dado corrompido"

identificar_object(df)

Colunas do tipo 'object':
- sepal length (cm)